-- Generated by `prisma migrate dev --create-only`, then edited by hand:
--   BIGSERIAL -> BIGINT GENERATED ALWAYS AS IDENTITY (SQL-standard identity, see docs/erd.md 5.1)

-- CreateTable
CREATE TABLE "currencies" (
    "code" CHAR(3) NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "symbol" VARCHAR(5) NOT NULL,
    "decimals" SMALLINT NOT NULL DEFAULT 2,

    CONSTRAINT "currencies_pkey" PRIMARY KEY ("code")
);

-- CreateTable
CREATE TABLE "users" (
    "user_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "email" VARCHAR(255) NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "display_name" VARCHAR(100) NOT NULL,
    "default_currency" CHAR(3) NOT NULL,
    "timezone" VARCHAR(50) NOT NULL DEFAULT 'Asia/Bangkok',
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("user_id")
);

-- CreateTable
CREATE TABLE "refresh_tokens" (
    "token_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "token_hash" CHAR(64) NOT NULL,
    "expires_at" TIMESTAMPTZ(6) NOT NULL,
    "revoked_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "refresh_tokens_pkey" PRIMARY KEY ("token_id")
);

-- CreateTable
CREATE TABLE "wallets" (
    "wallet_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "currency_code" CHAR(3) NOT NULL,
    "initial_balance" DECIMAL(18,2) NOT NULL DEFAULT 0,
    "is_archived" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "wallets_pkey" PRIMARY KEY ("wallet_id")
);

-- CreateTable
CREATE TABLE "categories" (
    "category_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT,
    "parent_id" BIGINT,
    "name" VARCHAR(100) NOT NULL,
    "type" VARCHAR(10) NOT NULL,
    "icon" VARCHAR(50),
    "color" CHAR(7),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "categories_pkey" PRIMARY KEY ("category_id")
);

-- CreateTable
CREATE TABLE "transactions" (
    "transaction_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "type" VARCHAR(10) NOT NULL,
    "wallet_id" BIGINT NOT NULL,
    "to_wallet_id" BIGINT,
    "category_id" BIGINT,
    "amount" DECIMAL(18,2) NOT NULL,
    "to_amount" DECIMAL(18,2),
    "note" VARCHAR(255),
    "occurred_at" TIMESTAMPTZ(6) NOT NULL,
    "recurring_id" BIGINT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "transactions_pkey" PRIMARY KEY ("transaction_id")
);

-- CreateTable
CREATE TABLE "budgets" (
    "budget_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "month" DATE NOT NULL,
    "limit_amount" DECIMAL(18,2) NOT NULL,
    "alert_percent" SMALLINT NOT NULL DEFAULT 80,

    CONSTRAINT "budgets_pkey" PRIMARY KEY ("budget_id")
);

-- CreateTable
CREATE TABLE "tags" (
    "tag_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "name" VARCHAR(50) NOT NULL,

    CONSTRAINT "tags_pkey" PRIMARY KEY ("tag_id")
);

-- CreateTable
CREATE TABLE "transaction_tags" (
    "transaction_id" BIGINT NOT NULL,
    "tag_id" BIGINT NOT NULL,

    CONSTRAINT "pk_transaction_tags" PRIMARY KEY ("transaction_id","tag_id")
);

-- CreateTable
CREATE TABLE "recurring_transactions" (
    "recurring_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "user_id" BIGINT NOT NULL,
    "type" VARCHAR(10) NOT NULL,
    "wallet_id" BIGINT NOT NULL,
    "category_id" BIGINT NOT NULL,
    "amount" DECIMAL(18,2) NOT NULL,
    "note" VARCHAR(255),
    "frequency" VARCHAR(10) NOT NULL,
    "next_run_date" DATE NOT NULL,
    "end_date" DATE,
    "is_active" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "recurring_transactions_pkey" PRIMARY KEY ("recurring_id")
);

-- CreateTable
CREATE TABLE "attachments" (
    "attachment_id" BIGINT GENERATED ALWAYS AS IDENTITY,
    "transaction_id" BIGINT NOT NULL,
    "storage_key" VARCHAR(500) NOT NULL,
    "original_name" VARCHAR(255) NOT NULL,
    "mime_type" VARCHAR(100) NOT NULL,
    "size_bytes" INTEGER NOT NULL,
    "uploaded_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "attachments_pkey" PRIMARY KEY ("attachment_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "uq_users_email" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "uq_refresh_tokens_hash" ON "refresh_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "idx_refresh_tokens_user" ON "refresh_tokens"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_wallets_user_name" ON "wallets"("user_id", "name");

-- CreateIndex
CREATE INDEX "idx_categories_user" ON "categories"("user_id");

-- CreateIndex
CREATE INDEX "idx_categories_parent" ON "categories"("parent_id");

-- CreateIndex
CREATE INDEX "idx_tx_user_date" ON "transactions"("user_id", "occurred_at" DESC);

-- CreateIndex
CREATE INDEX "idx_tx_wallet" ON "transactions"("wallet_id");

-- CreateIndex
CREATE INDEX "idx_tx_to_wallet" ON "transactions"("to_wallet_id");

-- CreateIndex
CREATE INDEX "idx_tx_category" ON "transactions"("category_id");

-- CreateIndex
CREATE INDEX "idx_tx_recurring" ON "transactions"("recurring_id");

-- CreateIndex
CREATE INDEX "idx_budgets_category" ON "budgets"("category_id");

-- CreateIndex
CREATE UNIQUE INDEX "uq_budgets_user_category_month" ON "budgets"("user_id", "category_id", "month");

-- CreateIndex
CREATE UNIQUE INDEX "uq_tags_user_name" ON "tags"("user_id", "name");

-- CreateIndex
CREATE INDEX "idx_transaction_tags_tag" ON "transaction_tags"("tag_id");

-- CreateIndex
CREATE INDEX "idx_recurring_user" ON "recurring_transactions"("user_id");

-- CreateIndex
CREATE INDEX "idx_recurring_wallet" ON "recurring_transactions"("wallet_id");

-- CreateIndex
CREATE INDEX "idx_recurring_category" ON "recurring_transactions"("category_id");

-- CreateIndex
CREATE INDEX "idx_recurring_due" ON "recurring_transactions"("next_run_date");

-- CreateIndex
CREATE INDEX "idx_attachments_tx" ON "attachments"("transaction_id");

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "fk_users_currency" FOREIGN KEY ("default_currency") REFERENCES "currencies"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "refresh_tokens" ADD CONSTRAINT "fk_refresh_tokens_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wallets" ADD CONSTRAINT "fk_wallets_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "wallets" ADD CONSTRAINT "fk_wallets_currency" FOREIGN KEY ("currency_code") REFERENCES "currencies"("code") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "categories" ADD CONSTRAINT "fk_categories_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "categories" ADD CONSTRAINT "fk_categories_parent" FOREIGN KEY ("parent_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "fk_tx_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "fk_tx_wallet" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("wallet_id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "fk_tx_to_wallet" FOREIGN KEY ("to_wallet_id") REFERENCES "wallets"("wallet_id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "fk_tx_category" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transactions" ADD CONSTRAINT "fk_tx_recurring" FOREIGN KEY ("recurring_id") REFERENCES "recurring_transactions"("recurring_id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "budgets" ADD CONSTRAINT "fk_budgets_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "budgets" ADD CONSTRAINT "fk_budgets_category" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tags" ADD CONSTRAINT "fk_tags_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transaction_tags" ADD CONSTRAINT "fk_transaction_tags_tx" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("transaction_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "transaction_tags" ADD CONSTRAINT "fk_transaction_tags_tag" FOREIGN KEY ("tag_id") REFERENCES "tags"("tag_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recurring_transactions" ADD CONSTRAINT "fk_recurring_user" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recurring_transactions" ADD CONSTRAINT "fk_recurring_wallet" FOREIGN KEY ("wallet_id") REFERENCES "wallets"("wallet_id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "recurring_transactions" ADD CONSTRAINT "fk_recurring_category" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "attachments" ADD CONSTRAINT "fk_attachments_tx" FOREIGN KEY ("transaction_id") REFERENCES "transactions"("transaction_id") ON DELETE CASCADE ON UPDATE CASCADE;
